# Usando a imagem base Debian 12 Stable (Bookworm)
FROM debian:stable

# Atualizar repositórios e instalar pacotes necessários
RUN apt-get update && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    xfce4 xfce4-goodies \
    x11vnc xvfb \
    curl \
    terminator \
    chromium=114.0.0.0-1~deb11u1 \
    chromium=102.0.0.0-1~deb11u1 \
    firefox=114.0+build4-0ubuntu1 \
    firefox=102.0+build4-0ubuntu0.23.04.1 && \
    apt-get clean && \
    apt-get autoremove -y && \
    rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

# Configurando senha para acesso via VNC
RUN mkdir ~/.vnc && \
    x11vnc -storepasswd 294756 ~/.vnc/passwd

# Configurações do ambiente
ENV DISPLAY=:0 \
    VNC_COL_DEPTH=24 \
    VNC_RESOLUTION=1280x800

# Criando um diretório de trabalho
WORKDIR /app

# Instalando o Node.js LTS e NPM (substituir versão conforme necessário)
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs npm

# Comando de inicialização
CMD Xvfb $DISPLAY -screen 0 $VNC_RESOLUTION -ac +extension RANDR && \
    xfce4-session & \
    x11vnc -forever -usepw -create && \
    terminator & \
    firefox & firefox102 & chromium & chromium102 & tail -f /dev/null

